# Generated by Django 4.2.4 on 2023-08-20 18:00

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('eno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
                ('address_street', models.CharField(max_length=300)),
                ('address_city', models.CharField(max_length=300)),
                ('address_state', models.CharField(max_length=2)),
                ('address_zip', models.IntegerField(max_length=5)),
                ('bio', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('booth_number', models.IntegerField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eno.participant')),
            ],
            bases=('eno.participant',),
        ),
    ]
