# Generated by Django 4.2.4 on 2023-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eno', '0002_participant_craft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='address_zip',
            field=models.IntegerField(),
        ),
    ]
