# Generated by Django 4.2.4 on 2023-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eno', '0003_alter_participant_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='booth_number',
            field=models.IntegerField(),
        ),
    ]
