# Generated by Django 4.2.4 on 2023-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eno', '0004_alter_participant_booth_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
