# Generated by Django 4.2.4 on 2023-08-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eno', '0005_craft_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='number',
        ),
        migrations.AlterField(
            model_name='participant',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
