# Generated by Django 4.2.4 on 2023-08-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eno', '0006_remove_craft_number_alter_participant_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='medium',
            field=models.CharField(choices=[('clay', 'ceramics'), ('wood', 'wood'), ('paint', 'paint'), ('drawing', 'drawing'), ('textile', 'textile')], default='clay'),
            preserve_default=False,
        ),
    ]
